---
--- Generated by Luanalysis
--- Created by luis3.
--- DateTime: 02/12/2021 10:39
---

print("Hello, world!")

-- Single line comments in Lua start with double hyphen.

--[[ Multiple line comments start
with double hyphen and two square brackets.
  and end with two square brackets. ]]



