---
--- Generated by Luanalysis
--- Created by luis3.
--- DateTime: 02/12/2021 11:06
---

a="single 'quoted' string and double \"quoted\" string inside"
b='single \'quoted\' string and double "quoted" string inside'
c= [[ multiple line
with 'single'
and "double" quoted strings inside.]]

print(a)
print(b)
print(c)