---
--- Generated by Luanalysis
--- Created by luis3.
--- DateTime: 02/12/2021 11:37
---

-- Simple table creation.

a={} -- {} Leere Table
b={1,2,3} -- Erstellt eine Table mit 1,2,3
c={"a","b","c"} -- Erstellt eine Table mit a, b, c
print(a,b,c) -- Tables werden wie Java-Objekte nicht direkt gedruckt, es bedarf mehr Arbeit!
