---
--- Generated by Luanalysis
--- Created by luis3.
--- DateTime: 02/12/2021 10:54
---
-- Variables hold values which have types, variables don't have types.

a=1
b="abc"
c={}
d=print

print(type(a))
print(type(b))
print(type(c))
print(type(d))